find_path(ASIO_SERIAL_DEVICE_INCLUDE_DIR asio_serial_device/ASIOSerialDevice.h
  PATHS "${CMAKE_CURRENT_LIST_DIR}/../include"
  PATH_SUFFIXES asio_serial_device)
set(ASIO_SERIAL_DEVICE_INCLUDE_DIRS ${ASIO_SERIAL_DEVICE_INCLUDE_DIR})

find_library(ASIO_SERIAL_DEVICE_LIBRARY NAMES asio_serial_device
  PATHS "${CMAKE_CURRENT_LIST_DIR}/../lib")
set(ASIO_SERIAL_DEVICE_LIBRARIES ${ASIO_SERIAL_DEVICE_LIBRARY})

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(ASIO_SERIAL_DEVICE
  DEFAULT_MSG
  ASIO_SERIAL_DEVICE_LIBRARY
  ASIO_SERIAL_DEVICE_INCLUDE_DIR)

mark_as_advanced(ASIO_SERIAL_DEVICE_INCLUDE_DIR ASIO_SERIAL_DEVICE_LIBRARY)
